# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target ‘SmartBit Cashier’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartBit Cashier
pod 'Alamofire'
#pod 'RealmSwift', '~> 2.0'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
#pod 'Firebase/Auth'
#pod 'Firebase/Storage'
pod 'SwiftyJSON', '~> 3.1'
end
