# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘PlayGame’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayGame
#pod 'Alamofire', '~> 4.1’
#pod 'RealmSwift', '~> 2.0'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
#pod 'Firebase/Auth'
#pod 'Firebase/Storage'
pod 'SwiftyJSON', '~> 3.1'
end
